name: Continuous Integration

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [develop]

jobs:
    run-tests:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - uses: actions/checkout@v2
            - run: composer install
            - run: ./vendor/bin/phpunit

    static-analysis:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: composer install
            - run: ./vendor/bin/phan
